export const TEXT_ADJUSTED_HEIGHT = 40;
export const TEXT_ADJUSTED_WIDTH = 40;
export const SELECTION_PADDING_PX = 5;
export const SELECTION_TOLERENCE_PX= 5;
export enum WsMessageType {
    JOIN = "JOIN_ROOM",
    LEAVE = "LEAVE_ROOM",
    DRAW = "DRAW_SHAPE",
    ERASE = "ERASE",
    UPDATE = "UPDATE",
    SHAPE_DRAGGING = "SHAPE_DRAG_UPDATE",
    SHAPE_DRAWING = "SHAPE_DRAW_UPDATE"
}